apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIiA6ICJkZXNrdG9wIiwKICAiYXV0aHMiOiB7CgkiZ2hjci5pbyI6IHsKCQkiYXV0aCI6ImEyRjBiMlJtYjNKaGJtOWtPbWRvY0Y5cFZrRjBVMEZvY2pGeVoyWklaRFJKTnpWcFRYRXhaREJvTWtwS1YxWXdaMnBOVmxZPSIKCX0KIH0KfQo=
type: kubernetes.io/dockerconfigjson
